### PR TITLE
Option to set Done & Clear button text

### PR DESCRIPTION
**Pull request by shrunyan**
I added the option to provide text for the done & clear buttons.  I've create a tag for this in my fork because I'm going to use this in a production application. https://github.com/shrunyan/anytime/releases/tag/v0.4.3

P.S. this is my first pull request so please let me know if I'm not doing anything correctly. Thanks.

### CODE REVIEW

**Comment by shrunyan** [comment]
I added another option for providing a callback that is passed the selected time. Realizing these should have been separate branches and pull requests. I can break these a part if desired.

**Comment by bengourley** [comment]
Hi, firstly thanks for the contribution! Decent first pull request.

I like the idea of being able to customise the button text. There is a bunch of work i18n that needs to be done with this module but that is a good first step.

As you mention, it would have been good to isolate the features in different requests. As far as the done callback is concerned, this is something I wouldn't want to merge. The picker is an event emitter that emits 'change' events when the underlying date changes, you listen like so:

```js
picker.on('change', function (d) { console.log(d) }
```

This isn't documented in the readme nor is it in the example so you can be excused for not noticing it! I'm sorry that the documentation is lacking. We've been using this module quite a lot in its pre-stable version stage and it is now nearly ready for a final push and a bit of a polish documentation-wise.

**Comment by klaemo** [comment]
I'd really love to customize the button's text. What needs to be done to get this merged? :)

**Comment by bengourley** [comment]
I have opened a new issue at #26 which I will get to when I can.

**Pull request closed without merging**
