### PR TITLE
Allow customisation of button text

### PR DESCRIPTION
**Pull request by klaemo**
As discussed in #26 
- added 'doneText' and 'clearText' option
- changed clear-btn class

I changed the class of the clear button to 'anytime-picker__button--clear'. Previously it was
'anytime-picker__button--next', which might have been by mistake?
I can easily reverse this change if wanted.

Also, I don't know where to update the documentation.

### CODE REVIEW

**Comment by klaemo** [comment]
The class name change could be considered breaking behavior.

**Comment by bengourley** [comment]
Thanks. I'll update the documentation and publish a new version.

**Comment by bengourley** [comment]
Version 1.0.1 is published, documentation updated. Thanks for your contribution!

**Comment by klaemo** [comment]
Cool, thank you for this module :)

**Comment by bengourley** [comment]
Pleasure :tada:

**Pull request merged**
